// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * Blockefy - single-file build for Remix.
 *
 * AUTO-GENERATED by scripts/compile-contract.js from contracts/Blockefy.sol with
 * the OpenZeppelin v5 sources inlined. Do not edit here: edit Blockefy.sol and
 * re-run `npm run compile:contract`.
 *
 * Remix compiler settings (MUST match, or the deployed bytecode will differ and
 * the backend's bytecode check will reject it):
 *   - Solidity 0.8.x (^0.8.20)
 *   - EVM version: shanghai
 *   - Enable optimization: YES
 *   - Runs: 200
 *   - Enable viaIR: YES
 *
 * Verify with: npm run verify:remix
 */



// ===== contracts/Blockefy.sol =====

/**
 * Blockefy - single-file build for Remix.
 *
 * AUTO-GENERATED by scripts/compile-contract.js from contracts/Blockefy.sol with
 * the OpenZeppelin v5 sources inlined. Do not edit here: edit Blockefy.sol and
 * re-run `npm run compile:contract`.
 *
 * Remix compiler settings (MUST match, or the deployed bytecode will differ and
 * the backend's bytecode check will reject it):
 *   - Solidity 0.8.x (^0.8.20)
 *   - EVM version: shanghai
 *   - Enable optimization: YES
 *   - Runs: 200
 *   - Enable viaIR: YES
 *
 * Verify with: npm run verify:remix
 */

// ===== @openzeppelin\contracts\utils\Context.sol =====
// OpenZeppelin Contracts (last updated v5.0.1) (utils/Context.sol)

/**
 * @dev Provides information about the current execution context, including the
 * sender of the transaction and its data. While these are generally available
 * via msg.sender and msg.data, they should not be accessed in such a direct
 * manner, since when dealing with meta-transactions the account sending and
 * paying for execution may not be the actual sender (as far as an application
 * is concerned).
 *
 * This contract is only required for intermediate, library-like contracts.
 */
abstract contract Context {
    function _msgSender() internal view virtual returns (address) {
        return msg.sender;
    }

    function _msgData() internal view virtual returns (bytes calldata) {
        return msg.data;
    }

    function _contextSuffixLength() internal view virtual returns (uint256) {
        return 0;
    }
}

// ===== @openzeppelin/contracts/access/Ownable.sol =====
// OpenZeppelin Contracts (last updated v5.0.0) (access/Ownable.sol)

/**
 * @dev Contract module which provides a basic access control mechanism, where
 * there is an account (an owner) that can be granted exclusive access to
 * specific functions.
 *
 * The initial owner is set to the address provided by the deployer. This can
 * later be changed with {transferOwnership}.
 *
 * This module is used through inheritance. It will make available the modifier
 * `onlyOwner`, which can be applied to your functions to restrict their use to
 * the owner.
 */
abstract contract Ownable is Context {
    address private _owner;

    /**
     * @dev The caller account is not authorized to perform an operation.
     */
    error OwnableUnauthorizedAccount(address account);

    /**
     * @dev The owner is not a valid owner account. (eg. `address(0)`)
     */
    error OwnableInvalidOwner(address owner);

    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);

    /**
     * @dev Initializes the contract setting the address provided by the deployer as the initial owner.
     */
    constructor(address initialOwner) {
        if (initialOwner == address(0)) {
            revert OwnableInvalidOwner(address(0));
        }
        _transferOwnership(initialOwner);
    }

    /**
     * @dev Throws if called by any account other than the owner.
     */
    modifier onlyOwner() {
        _checkOwner();
        _;
    }

    /**
     * @dev Returns the address of the current owner.
     */
    function owner() public view virtual returns (address) {
        return _owner;
    }

    /**
     * @dev Throws if the sender is not the owner.
     */
    function _checkOwner() internal view virtual {
        if (owner() != _msgSender()) {
            revert OwnableUnauthorizedAccount(_msgSender());
        }
    }

    /**
     * @dev Leaves the contract without owner. It will not be possible to call
     * `onlyOwner` functions. Can only be called by the current owner.
     *
     * NOTE: Renouncing ownership will leave the contract without an owner,
     * thereby disabling any functionality that is only available to the owner.
     */
    function renounceOwnership() public virtual onlyOwner {
        _transferOwnership(address(0));
    }

    /**
     * @dev Transfers ownership of the contract to a new account (`newOwner`).
     * Can only be called by the current owner.
     */
    function transferOwnership(address newOwner) public virtual onlyOwner {
        if (newOwner == address(0)) {
            revert OwnableInvalidOwner(address(0));
        }
        _transferOwnership(newOwner);
    }

    /**
     * @dev Transfers ownership of the contract to a new account (`newOwner`).
     * Internal function without access restriction.
     */
    function _transferOwnership(address newOwner) internal virtual {
        address oldOwner = _owner;
        _owner = newOwner;
        emit OwnershipTransferred(oldOwner, newOwner);
    }
}

// ===== @openzeppelin/contracts/utils/ReentrancyGuard.sol =====
// OpenZeppelin Contracts (last updated v5.0.0) (utils/ReentrancyGuard.sol)

/**
 * @dev Contract module that helps prevent reentrant calls to a function.
 *
 * Inheriting from `ReentrancyGuard` will make the {nonReentrant} modifier
 * available, which can be applied to functions to make sure there are no nested
 * (reentrant) calls to them.
 *
 * Note that because there is a single `nonReentrant` guard, functions marked as
 * `nonReentrant` may not call one another. This can be worked around by making
 * those functions `private`, and then adding `external` `nonReentrant` entry
 * points to them.
 *
 * TIP: If you would like to learn more about reentrancy and alternative ways
 * to protect against it, check out our blog post
 * https://blog.openzeppelin.com/reentrancy-after-istanbul/[Reentrancy After Istanbul].
 */
abstract contract ReentrancyGuard {
    // Booleans are more expensive than uint256 or any type that takes up a full
    // word because each write operation emits an extra SLOAD to first read the
    // slot's contents, replace the bits taken up by the boolean, and then write
    // back. This is the compiler's defense against contract upgrades and
    // pointer aliasing, and it cannot be disabled.

    // The values being non-zero value makes deployment a bit more expensive,
    // but in exchange the refund on every call to nonReentrant will be lower in
    // amount. Since refunds are capped to a percentage of the total
    // transaction's gas, it is best to keep them low in cases like this one, to
    // increase the likelihood of the full refund coming into effect.
    uint256 private constant NOT_ENTERED = 1;
    uint256 private constant ENTERED = 2;

    uint256 private _status;

    /**
     * @dev Unauthorized reentrant call.
     */
    error ReentrancyGuardReentrantCall();

    constructor() {
        _status = NOT_ENTERED;
    }

    /**
     * @dev Prevents a contract from calling itself, directly or indirectly.
     * Calling a `nonReentrant` function from another `nonReentrant`
     * function is not supported. It is possible to prevent this from happening
     * by making the `nonReentrant` function external, and making it call a
     * `private` function that does the actual work.
     */
    modifier nonReentrant() {
        _nonReentrantBefore();
        _;
        _nonReentrantAfter();
    }

    function _nonReentrantBefore() private {
        // On the first call to nonReentrant, _status will be NOT_ENTERED
        if (_status == ENTERED) {
            revert ReentrancyGuardReentrantCall();
        }

        // Any calls to nonReentrant after this point will fail
        _status = ENTERED;
    }

    function _nonReentrantAfter() private {
        // By storing the original value once again, a refund is triggered (see
        // https://eips.ethereum.org/EIPS/eip-2200)
        _status = NOT_ENTERED;
    }

    /**
     * @dev Returns true if the reentrancy guard is currently set to "entered", which indicates there is a
     * `nonReentrant` function in the call stack.
     */
    function _reentrancyGuardEntered() internal view returns (bool) {
        return _status == ENTERED;
    }
}

// ===== @openzeppelin/contracts/utils/Pausable.sol =====
// OpenZeppelin Contracts (last updated v5.0.0) (utils/Pausable.sol)

/**
 * @dev Contract module which allows children to implement an emergency stop
 * mechanism that can be triggered by an authorized account.
 *
 * This module is used through inheritance. It will make available the
 * modifiers `whenNotPaused` and `whenPaused`, which can be applied to
 * the functions of your contract. Note that they will not be pausable by
 * simply including this module, only once the modifiers are put in place.
 */
abstract contract Pausable is Context {
    bool private _paused;

    /**
     * @dev Emitted when the pause is triggered by `account`.
     */
    event Paused(address account);

    /**
     * @dev Emitted when the pause is lifted by `account`.
     */
    event Unpaused(address account);

    /**
     * @dev The operation failed because the contract is paused.
     */
    error EnforcedPause();

    /**
     * @dev The operation failed because the contract is not paused.
     */
    error ExpectedPause();

    /**
     * @dev Initializes the contract in unpaused state.
     */
    constructor() {
        _paused = false;
    }

    /**
     * @dev Modifier to make a function callable only when the contract is not paused.
     *
     * Requirements:
     *
     * - The contract must not be paused.
     */
    modifier whenNotPaused() {
        _requireNotPaused();
        _;
    }

    /**
     * @dev Modifier to make a function callable only when the contract is paused.
     *
     * Requirements:
     *
     * - The contract must be paused.
     */
    modifier whenPaused() {
        _requirePaused();
        _;
    }

    /**
     * @dev Returns true if the contract is paused, and false otherwise.
     */
    function paused() public view virtual returns (bool) {
        return _paused;
    }

    /**
     * @dev Throws if the contract is paused.
     */
    function _requireNotPaused() internal view virtual {
        if (paused()) {
            revert EnforcedPause();
        }
    }

    /**
     * @dev Throws if the contract is not paused.
     */
    function _requirePaused() internal view virtual {
        if (!paused()) {
            revert ExpectedPause();
        }
    }

    /**
     * @dev Triggers stopped state.
     *
     * Requirements:
     *
     * - The contract must not be paused.
     */
    function _pause() internal virtual whenNotPaused {
        _paused = true;
        emit Paused(_msgSender());
    }

    /**
     * @dev Returns to normal state.
     *
     * Requirements:
     *
     * - The contract must be paused.
     */
    function _unpause() internal virtual whenPaused {
        _paused = false;
        emit Unpaused(_msgSender());
    }
}

// ===== contracts/Blockefy.sol =====

/**
 * @title Blockefy
 * @notice A decentralized escrow smart contract for the Blockefy freelancing platform.
 *
 * @dev This contract manages the entire lifecycle of a freelance gig/project between a
 *      Client (buyer) and a Freelancer (seller) using native ETH (on a testnet for now).
 *
 *      --- HIGH-LEVEL FLOW ---
 *      1. CLIENT creates a project with a type: "FixClaim" (one-time payment) or
 *         "Milestones" (multiple milestone-based payments).
 *      2. FREELANCER submits a proposal (off-chain) with payment details. Once the
 *         CLIENT approves that proposal, the project is officially CREATED on-chain
 *         and the freelancer is assigned.
 *      3. For a Milestones project, the FREELANCER creates milestones with their
 *         individual amounts. Milestones may be added at any point in the project
 *         lifecycle, including after funding or after a previous phase completed.
 *      4. CLIENT deposits the exact amount of the next unfunded milestone. Deposits
 *         are strictly ordered, capped to the milestone amount, and cannot over-fund.
 *      5. FREELANCER completes a milestone and marks it complete. The CLIENT then
 *         reviews THAT milestone:
 *            - "No changes required"  -> that milestone is approved for release.
 *            - "Changes required"     -> the milestone is re-opened for rework and
 *                                         the review window/deadline are extended.
 *      6. If the CLIENT does NOT review within the review window, the milestone is
 *         released to the freelancer automatically (time-based safeguard).
 *      7. Milestones are paid in STRICT SEQUENTIAL order (1 -> 2 -> 3 ...). A milestone
 *         cannot be claimed until all previous milestones are claimed, so only one
 *         milestone is ever "in review" at a time.
 *      8. If the project deadline passes, the CLIENT may extend the deadline or
 *         retrieve any escrowed funds that are not already under review.
 *      9. A dispute may be opened by the CLIENT or the FREELANCER (or the ADMIN),
 *         which locks all payments until the ADMIN resolves it.
 *
 *      --- REVIEW STATE MODEL ---
 *      Approval is tracked PER MILESTONE (`Milestone.isApproved`), never as a sticky
 *      project-wide flag. Because claiming is strictly sequential, at most one
 *      milestone is in review at a time, which makes the project-level
 *      `lastReviewAt` review timer correct while keeping the approve/revise cycle
 *      fully independent for every milestone.
 *
 *      --- SAFETY ---
 *      - Every value-moving function is `nonReentrant` and follows checks-effects-
 *        interactions.
 *      - Escrowed principal is tracked in `totalEscrowed`; `sweepSurplus` can only
 *        ever remove ETH that is NOT escrowed, so it can never drain client funds.
 *      - Over-deposits are impossible: a deposit must exactly equal the amount of
 *        the next unfunded milestone.
 *
 *      NOTE: Platform fees are currently 0%. The contract is structured so a 2%
 *            platform fee can be enabled later via setPlatformFee().
 */

// -----------------------------------------------------------------------------
//  Import: OpenZeppelin v5 (access/Ownable, utils/ReentrancyGuard, utils/Pausable)
// -----------------------------------------------------------------------------



contract Blockefy is ReentrancyGuard, Ownable, Pausable {
    // =========================================================================
    //  STATE VARIABLES
    // =========================================================================

    /// @notice Project statuses used throughout the contract lifecycle.
    enum ProjectStatus {
        Created,      // 0 - project exists, freelancer approved, no escrow yet
        Funded,       // 1 - escrow received, no work submitted yet
        InProgress,   // 2 - work is being delivered / under review
        Completed,    // 3 - all milestones released (reopenable by adding a milestone)
        Cancelled,    // 4 - client got a refund / project abandoned
        Disputed      // 5 - payments locked pending admin resolution
    }

    /// @notice The type of payment model a project uses.
    enum ProjectType {
        FixClaim,     // 0 - one-time, single payment for the whole project
        Milestones    // 1 - multiple sequential milestone payments
    }

    /// @notice Holds the details of a single milestone within a project.
    struct Milestone {
        uint256 id;            // Unique milestone id (incremental, global counter)
        string description;    // Short description of the work for this milestone
        uint256 amount;        // ETH value (in wei) locked for this milestone
        bool isFunded;         // true once the client has escrowed `amount` for it
        bool isCompleted;      // true once the freelancer marks the work delivered
        bool isApproved;       // true once the CLIENT approves THIS milestone
        bool isClaimed;        // true once the payment for this milestone is released
        bool isDisputed;       // true if this milestone is part of an active dispute
        uint256 claimedAt;     // block.timestamp when payment was released
    }

    /// @notice Holds all the data for a single project.
    struct Project {
        uint256 id;                    // Unique project id (incremental counter)
        address client;                // The buyer who created the project
        address freelancer;            // The seller assigned after proposal approval (0x0 until then)
        ProjectType projectType;       // FixClaim or Milestones
        ProjectStatus status;          // Current lifecycle status
        uint256 fixClaimAmount;        // For FixClaim projects: the escrowed total
        uint256[] milestoneIds;        // Ordered list of milestone ids (sequential)
        uint256 totalFunded;           // Total ETH currently held in escrow for this project
        uint256 deadline;              // block.timestamp before which the project should be delivered
        uint256 reviewWindow;          // Seconds allowed for client review before auto-release
        uint256 lastReviewAt;          // Last time a review (approve/change) happened
        uint256 changesCount;          // How many times "changes required" was requested
        bool isSubmitted;              // true when work is currently submitted for review
        bool isDeliverableAccepted;    // true when the current submission is approved
        bool isProjectFunded;          // true once the first escrow deposit happens
        string metadataHash;           // Optional off-chain pointer (IPFS/CID) for project details
    }

    /// @notice Counter for generating unique project ids (starts at 1).
    uint256 public projectCounter;

    /// @notice Counter for generating unique milestone ids (starts at 1).
    uint256 public milestoneCounter;

    /// @notice projectId => Project  (mapping of all projects).
    mapping(uint256 => Project) public projects;

    /// @notice milestoneId => Milestone  (mapping of all milestones).
    mapping(uint256 => Milestone) public milestones;

    /// @notice projectId => milestoneId => whether that milestone belongs to this project.
    mapping(uint256 => mapping(uint256 => bool)) public projectMilestones;

    /// @notice Total ETH held on this contract that is held in escrow for clients.
    /// @dev Used by `sweepSurplus` so surplus/stray ETH can never be taken from escrow.
    uint256 public totalEscrowed;

    /// @notice Default review window (in seconds). 15 days = 15 * 24 * 60 * 60.
    uint256 public constant DEFAULT_REVIEW_WINDOW = 15 days;

    /// @notice Default delivery window applied when a project is created (30 days).
    uint256 public constant DEFAULT_DEADLINE = 30 days;

    /// @notice Maximum number of "changes required" cycles per project.
    uint256 public constant MAX_REVISIONS = 10;

    /// @notice Maximum length (in bytes) of a milestone description.
    /// @dev Bounds the storage cost of `createMilestone`. Without this cap a long
    ///      description can cost >1.5M gas and become impossible to relay within a
    ///      sane gas limit, bricking the project. 500 bytes is a full paragraph.
    uint256 public constant MAX_DESCRIPTION_LENGTH = 500;

    /// @notice Maximum single deadline extension, in days.
    /// @dev `extraDays` is multiplied by `1 days` before being added to the
    ///      deadline. An unbounded value overflows and reverts, which would make
    ///      the extension permanently impossible to get right. Extensions are
    ///      additive, so a project can still be extended arbitrarily far by
    ///      calling this repeatedly.
    uint256 public constant MAX_DEADLINE_EXTENSION = 365;

    /// @notice Platform fee in basis points (e.g. 200 = 2%). 0 for now.
    uint256 public platformFeeBps;

    /// @notice Treasury address that receives platform fees.
    address public treasury;

    // =========================================================================
    //  EVENTS
    // =========================================================================

    event ProjectCreated(uint256 indexed projectId, address indexed client, ProjectType projectType);
    event ProjectApproved(uint256 indexed projectId, address indexed freelancer);
    event FundsDeposited(uint256 indexed projectId, address indexed client, uint256 amount, uint256 indexed milestoneId);
    event MilestoneCreated(uint256 indexed projectId, uint256 indexed milestoneId, uint256 amount);
    event MilestoneCompleted(uint256 indexed projectId, uint256 indexed milestoneId);
    event MilestoneClaimed(uint256 indexed projectId, uint256 indexed milestoneId, address indexed freelancer, uint256 amount);
    event DeliverableApproved(uint256 indexed projectId, uint256 indexed milestoneId);
    event ChangesRequested(uint256 indexed projectId, uint256 indexed milestoneId, uint256 newDeadline);
    event DeadlineExtended(uint256 indexed projectId, uint256 newDeadline);
    event FundsRefunded(uint256 indexed projectId, address indexed client, uint256 amount);
    event FixClaimSubmitted(uint256 indexed projectId);
    event DisputeOpened(uint256 indexed projectId, address indexed openedBy);
    event DisputeResolved(uint256 indexed projectId, bool toFreelancer);
    event SurplusSwept(address indexed to, uint256 amount);

    // =========================================================================
    //  MODIFIERS
    // =========================================================================

    modifier onlyClient(uint256 _projectId) {
        require(msg.sender == projects[_projectId].client, "Blockefy: caller is not the client");
        _;
    }

    modifier onlyFreelancer(uint256 _projectId) {
        require(msg.sender == projects[_projectId].freelancer, "Blockefy: caller is not the freelancer");
        _;
    }

    /// @dev Either party to the project, or the platform owner (admin).
    modifier onlyParticipant(uint256 _projectId) {
        Project storage project = projects[_projectId];
        require(
            msg.sender == project.client || msg.sender == project.freelancer || msg.sender == owner(),
            "Blockefy: caller is not a party to this project"
        );
        _;
    }

    /// @dev Ensures the project exists (was created).
    modifier projectExists(uint256 _projectId) {
        require(_projectId > 0 && _projectId <= projectCounter, "Blockefy: project does not exist");
        _;
    }

    /// @dev Ensures the project is NOT in a disputed state (so normal operations are paused).
    modifier notDisputed(uint256 _projectId) {
        require(projects[_projectId].status != ProjectStatus.Disputed, "Blockefy: project is under dispute");
        _;
    }

    /// @dev Ensures the project is still active (not cancelled / disputed).
    modifier onlyActive(uint256 _projectId) {
        require(
            projects[_projectId].status != ProjectStatus.Cancelled,
            "Blockefy: project is cancelled"
        );
        _;
    }

    // =========================================================================
    //  CONSTRUCTOR
    // =========================================================================

    /**
     * @notice Deploys the Blockefy contract.
     * @param _treasury The address that will receive platform fees (if enabled later).
     * @dev The deployer (msg.sender) automatically becomes the owner/ADMIN via Ownable.
     */
    constructor(address _treasury) Ownable(msg.sender) {
        require(_treasury != address(0), "Blockefy: invalid treasury");
        treasury = _treasury;
        platformFeeBps = 0;
    }

    // =========================================================================
    //  ADMIN (OWNER) FUNCTIONS
    // =========================================================================

    /// @notice Configures the platform fee (in basis points) collected on each release.
    function setPlatformFee(uint256 _platformFeeBps) external onlyOwner {
        require(_platformFeeBps <= 1000, "Blockefy: fee too high");
        platformFeeBps = _platformFeeBps;
    }

    /// @notice Updates the treasury address that receives platform fees.
    function setTreasury(address _treasury) external onlyOwner {
        require(_treasury != address(0), "Blockefy: invalid treasury");
        treasury = _treasury;
    }

    /// @notice Emergency stop for all new funding / milestone activity.
    function pause() external onlyOwner {
        _pause();
    }

    /// @notice Resumes normal operation.
    function unpause() external onlyOwner {
        _unpause();
    }

    /**
     * @notice Withdraws ETH that is NOT held in escrow (e.g. accidental transfers).
     * @param _to Recipient of the surplus.
     * @dev Guarded by `totalEscrowed` so it can never touch client funds. Only the
     *      surplus above the total escrowed principal can be swept.
     */
    function sweepSurplus(address payable _to) external onlyOwner nonReentrant {
        require(_to != address(0), "Blockefy: invalid recipient");
        uint256 balance = address(this).balance;
        require(balance > totalEscrowed, "Blockefy: no surplus to sweep");
        uint256 amount = balance - totalEscrowed;
        (bool ok, ) = _to.call{ value: amount }("");
        require(ok, "Blockefy: sweep failed");
        emit SurplusSwept(_to, amount);
    }

    // =========================================================================
    //  PROJECT CREATION & PROPOSAL APPROVAL
    // =========================================================================

    /**
     * @notice Creates a new project on-chain.
     * @param _projectType Whether it is a FixClaim (0) or Milestones (1) project.
     * @param _metadataHash Optional off-chain pointer (IPFS CID) to project details.
     * @return The newly created project id.
     * @dev Called by the CLIENT. The freelancer is assigned later via approveProject.
     */
    function createProject(ProjectType _projectType, string calldata _metadataHash)
        external
        whenNotPaused
        returns (uint256)
    {
        uint256 newId = ++projectCounter;

        projects[newId] = Project({
            id: newId,
            client: msg.sender,
            freelancer: address(0),
            projectType: _projectType,
            status: ProjectStatus.Created,
            fixClaimAmount: 0,
            milestoneIds: new uint256[](0),
            totalFunded: 0,
            deadline: block.timestamp + DEFAULT_DEADLINE,
            reviewWindow: DEFAULT_REVIEW_WINDOW,
            lastReviewAt: 0,
            changesCount: 0,
            isSubmitted: false,
            isDeliverableAccepted: false,
            isProjectFunded: false,
            metadataHash: _metadataHash
        });

        emit ProjectCreated(newId, msg.sender, _projectType);
        return newId;
    }

    /**
     * @notice Assigns a freelancer to a project once the CLIENT approves the proposal.
     * @param _projectId The project id.
     * @param _freelancer The address of the freelancer whose proposal was accepted.
     * @dev Called by the CLIENT after reviewing the freelancer's proposal (off-chain).
     *      The freelancer can only be set once.
     */
    function approveProject(uint256 _projectId, address _freelancer)
        external
        whenNotPaused
        projectExists(_projectId)
        onlyClient(_projectId)
    {
        Project storage project = projects[_projectId];
        require(project.freelancer == address(0), "Blockefy: project already has a freelancer");
        require(_freelancer != address(0) && _freelancer != msg.sender, "Blockefy: invalid freelancer");

        project.freelancer = _freelancer;
        emit ProjectApproved(_projectId, _freelancer);
    }

    // =========================================================================
    //  MILESTONE CREATION (FREELANCER)
    // =========================================================================

    /**
     * @notice Creates a milestone for a Milestones project.
     * @param _projectId The project id.
     * @param _description A short description of the milestone work.
     * @param _amount The ETH value (in wei) to be locked for this milestone.
     * @return The newly created milestone id.
     * @dev Called by the FREELANCER. Milestones may be created at any point in the
     *      project lifecycle (before funding, during work, or to add a new phase
     *      after a previous phase completed). Adding a milestone to a completed
     *      project re-opens it to InProgress.
     */
    function createMilestone(uint256 _projectId, string calldata _description, uint256 _amount)
        external
        whenNotPaused
        projectExists(_projectId)
        onlyFreelancer(_projectId)
        notDisputed(_projectId)
        onlyActive(_projectId)
        returns (uint256)
    {
        Project storage project = projects[_projectId];
        require(project.projectType == ProjectType.Milestones, "Blockefy: not a milestones project");
        require(_amount > 0, "Blockefy: milestone amount must be > 0");
        require(bytes(_description).length > 0, "Blockefy: milestone description required");
        require(
            bytes(_description).length <= MAX_DESCRIPTION_LENGTH,
            "Blockefy: description too long"
        );

        uint256 newMilestoneId = ++milestoneCounter;

        milestones[newMilestoneId] = Milestone({
            id: newMilestoneId,
            description: _description,
            amount: _amount,
            isFunded: false,
            isCompleted: false,
            isApproved: false,
            isClaimed: false,
            isDisputed: false,
            claimedAt: 0
        });

        projectMilestones[_projectId][newMilestoneId] = true;
        project.milestoneIds.push(newMilestoneId);

        // Adding work to a finished project re-opens it.
        if (project.status == ProjectStatus.Completed) {
            project.status = ProjectStatus.InProgress;
        }

        emit MilestoneCreated(_projectId, newMilestoneId, _amount);
        return newMilestoneId;
    }

    // =========================================================================
    //  FUNDING / ESCROW DEPOSIT (CLIENT)
    // =========================================================================

    /**
     * @notice Deposits ETH into escrow for the next unfunded milestone of a project.
     * @param _projectId The project id.
     * @dev Called by the CLIENT (payable). For a Milestones project the client must
     *      deposit the EXACT amount of the next unfunded milestone (strictly ordered).
     *      For a FixClaim project the client deposits the whole agreed amount once.
     *      Over-funding is not possible.
     */
    function depositFunds(uint256 _projectId)
        external
        payable
        whenNotPaused
        nonReentrant
        projectExists(_projectId)
        onlyClient(_projectId)
        notDisputed(_projectId)
        onlyActive(_projectId)
    {
        Project storage project = projects[_projectId];
        require(project.freelancer != address(0), "Blockefy: no freelancer assigned");
        require(msg.value > 0, "Blockefy: deposit must be > 0");

        uint256 fundedMilestoneId;

        if (project.projectType == ProjectType.FixClaim) {
            require(!project.isProjectFunded, "Blockefy: fix claim already funded");
            project.fixClaimAmount = msg.value;
            project.isProjectFunded = true;
            project.status = ProjectStatus.Funded;
        } else {
            // Strict order: the next unfunded, unclaimed milestone must be funded.
            fundedMilestoneId = _nextUnfundedMilestoneId(project);
            Milestone storage milestone = milestones[fundedMilestoneId];
            require(msg.value == milestone.amount, "Blockefy: deposit must equal milestone amount");
            milestone.isFunded = true;
            project.isProjectFunded = true;
            if (project.status == ProjectStatus.Created) {
                project.status = ProjectStatus.Funded;
            }
        }

        project.totalFunded += msg.value;
        totalEscrowed += msg.value;

        emit FundsDeposited(_projectId, msg.sender, msg.value, fundedMilestoneId);
    }

    // =========================================================================
    //  WORK SUBMISSION (FREELANCER)
    // =========================================================================

    /**
     * @notice Marks a funded milestone's work as delivered and opens the review window.
     * @param _projectId The project id.
     * @param _milestoneId The milestone id to mark complete.
     * @dev Called by the FREELANCER. Can be called again after a "changes required"
     *      revision, which re-opens the milestone for rework.
     */
    function completeMilestone(uint256 _projectId, uint256 _milestoneId)
        external
        whenNotPaused
        projectExists(_projectId)
        onlyFreelancer(_projectId)
        notDisputed(_projectId)
        onlyActive(_projectId)
    {
        Project storage project = projects[_projectId];
        _requireValidMilestone(project, _milestoneId);

        Milestone storage milestone = milestones[_milestoneId];
        require(milestone.isFunded, "Blockefy: milestone not funded");
        require(!milestone.isClaimed, "Blockefy: milestone already claimed");
        require(!milestone.isCompleted, "Blockefy: milestone already submitted");

        milestone.isCompleted = true;
        project.isSubmitted = true;
        project.status = ProjectStatus.InProgress;
        // Start the review window from this submission (auto-release safeguard).
        project.lastReviewAt = block.timestamp;

        emit MilestoneCompleted(_projectId, _milestoneId);
    }

    /**
     * @notice Submits the deliverable for a FixClaim (one-time payment) project.
     * @param _projectId The project id.
     * @dev Opens the review window so the client can approve or request changes.
     */
    function submitFixClaim(uint256 _projectId)
        external
        whenNotPaused
        projectExists(_projectId)
        onlyFreelancer(_projectId)
        notDisputed(_projectId)
        onlyActive(_projectId)
    {
        Project storage project = projects[_projectId];
        require(project.projectType == ProjectType.FixClaim, "Blockefy: not a fix claim project");
        require(project.isProjectFunded, "Blockefy: project not funded");
        require(!project.isSubmitted, "Blockefy: deliverable already submitted");

        project.isSubmitted = true;
        project.status = ProjectStatus.InProgress;
        project.lastReviewAt = block.timestamp;

        emit FixClaimSubmitted(_projectId);
    }

    // =========================================================================
    //  CLIENT REVIEW
    // =========================================================================

    /**
     * @notice Client approves a delivered milestone ("no changes required").
     * @param _projectId The project id.
     * @param _milestoneId The specific milestone being approved.
     * @dev Approval is recorded on the milestone itself, so approving one milestone
     *      never unlocks any other milestone.
     */
    function approveDeliverable(uint256 _projectId, uint256 _milestoneId)
        external
        whenNotPaused
        projectExists(_projectId)
        onlyClient(_projectId)
        notDisputed(_projectId)
        onlyActive(_projectId)
    {
        Project storage project = projects[_projectId];
        _requireValidMilestone(project, _milestoneId);

        Milestone storage milestone = milestones[_milestoneId];
        require(milestone.isCompleted, "Blockefy: no submission to approve");
        require(!milestone.isClaimed, "Blockefy: milestone already claimed");

        milestone.isApproved = true;
        project.isDeliverableAccepted = true;
        // Reset the review timer.
        project.lastReviewAt = block.timestamp;

        emit DeliverableApproved(_projectId, _milestoneId);
    }

    /**
     * @notice Client approves the deliverable of a FixClaim project.
     * @param _projectId The project id.
     * @dev FixClaim projects have no milestones, so approval is tracked at the
     *      project level for this payment model only.
     */
    function approveFixClaim(uint256 _projectId)
        external
        whenNotPaused
        projectExists(_projectId)
        onlyClient(_projectId)
        notDisputed(_projectId)
        onlyActive(_projectId)
    {
        Project storage project = projects[_projectId];
        require(project.projectType == ProjectType.FixClaim, "Blockefy: not a fix claim project");
        require(project.isSubmitted, "Blockefy: no submission to approve");
        require(project.totalFunded > 0, "Blockefy: nothing to release");

        project.isDeliverableAccepted = true;
        project.lastReviewAt = block.timestamp;

        emit DeliverableApproved(_projectId, 0);
    }

    /**
     * @notice Client requests changes on a delivered milestone.
     * @param _projectId The project id.
     * @param _milestoneId The specific milestone being sent back for rework.
     * @param _extraDays Number of days to add to the deadline for the revision.
     * @dev Re-opens the milestone so the freelancer can re-submit it, extends the
     *      project deadline, and restarts the review window.
     */
    function requestChanges(uint256 _projectId, uint256 _milestoneId, uint256 _extraDays)
        external
        whenNotPaused
        projectExists(_projectId)
        onlyClient(_projectId)
        notDisputed(_projectId)
        onlyActive(_projectId)
    {
        Project storage project = projects[_projectId];
        _requireValidMilestone(project, _milestoneId);

        require(_extraDays > 0, "Blockefy: extra days must be > 0");
        require(project.changesCount < MAX_REVISIONS, "Blockefy: revision limit reached");
        require(milestones[_milestoneId].isCompleted, "Blockefy: no submission to review");
        require(!milestones[_milestoneId].isClaimed, "Blockefy: milestone already claimed");

        // Re-open the milestone for rework (this is what makes re-submission possible).
        milestones[_milestoneId].isCompleted = false;
        milestones[_milestoneId].isApproved = false;

        project.isSubmitted = false;
        project.isDeliverableAccepted = false;
        _extendDeadline(project, _extraDays);
        project.lastReviewAt = block.timestamp;
        project.changesCount += 1;

        emit ChangesRequested(_projectId, _milestoneId, project.deadline);
    }

    /**
     * @notice Client extends the project deadline.
     * @param _projectId The project id.
     * @param _extraDays Number of days to extend.
     * @dev The extension is ADDITIVE: the deadline can only ever move later, never
     *      earlier, so an extension can never accidentally shorten a project.
     */
    function extendDeadline(uint256 _projectId, uint256 _extraDays)
        external
        projectExists(_projectId)
        onlyClient(_projectId)
        notDisputed(_projectId)
        onlyActive(_projectId)
    {
        require(_extraDays > 0, "Blockefy: extra days must be > 0");
        _extendDeadline(projects[_projectId], _extraDays);

        emit DeadlineExtended(_projectId, projects[_projectId].deadline);    }

    // =========================================================================
    //  MILESTONE CLAIMING (SEQUENTIAL)
    // =========================================================================

    /**
     * @notice Releases the payment for a milestone to the freelancer.
     * @param _projectId The project id.
     * @param _milestoneId The milestone id to claim.
     * @dev Milestones are released in STRICT SEQUENTIAL order (1 -> 2 -> 3). A
     *      milestone can only be claimed if it is funded, completed, all previous
     *      milestones are claimed, and it was approved by the client OR its review
     *      window lapsed.
     */
    function claimMilestone(uint256 _projectId, uint256 _milestoneId)
        external
        nonReentrant
        projectExists(_projectId)
        notDisputed(_projectId)
    {
        Project storage project = projects[_projectId];
        _requireValidMilestone(project, _milestoneId);
        require(msg.sender == project.client || msg.sender == project.freelancer, "Blockefy: unauthorized");

        Milestone storage milestone = milestones[_milestoneId];
        require(milestone.isFunded, "Blockefy: milestone not funded");
        require(!milestone.isClaimed, "Blockefy: milestone already claimed");
        require(milestone.isCompleted, "Blockefy: milestone not completed");

        // Enforce sequential claiming: previous milestones must all be claimed.
        _requirePreviousClaimed(project, _milestoneId);

        // Approved by client, or the review window lapsed (auto-release safeguard).
        require(milestone.isApproved || _reviewLapsed(project), "Blockefy: not approved yet");

        // Effects before interaction.
        // NOTE: `isCompleted` / `isApproved` are deliberately preserved as an
        // on-chain audit trail of what was delivered and accepted. Re-entry is
        // blocked by `isClaimed`, so keeping them cannot unlock a second payout.
        milestone.isClaimed = true;
        milestone.claimedAt = block.timestamp;

        project.totalFunded -= milestone.amount;
        totalEscrowed -= milestone.amount;

        // Reset the per-cycle review state so the NEXT milestone needs a fresh review.
        project.isSubmitted = false;
        project.isDeliverableAccepted = false;
        project.lastReviewAt = 0;

        _payFreelancer(project, milestone.amount);

        emit MilestoneClaimed(_projectId, _milestoneId, project.freelancer, milestone.amount);

        if (_isLastMilestone(project, _milestoneId)) {
            project.status = ProjectStatus.Completed;
        } else {
            project.status = ProjectStatus.InProgress;
        }
    }

    // =========================================================================
    //  FIX CLAIM (ONE-TIME PAYMENT RELEASE)
    // =========================================================================

    /**
     * @notice Releases the full one-time fix claim payment to the freelancer.
     * @param _projectId The project id.
     * @dev For FixClaim projects only. The freelancer submits via submitFixClaim, the
     *      client approves (or the review window lapses), then either party triggers
     *      this to release funds.
     */
    function fixClaim(uint256 _projectId)
        external
        nonReentrant
        projectExists(_projectId)
        notDisputed(_projectId)
        onlyActive(_projectId)
    {
        Project storage project = projects[_projectId];
        require(project.projectType == ProjectType.FixClaim, "Blockefy: not a fix claim project");
        require(msg.sender == project.client || msg.sender == project.freelancer, "Blockefy: unauthorized");
        require(project.isProjectFunded, "Blockefy: project not funded");
        require(project.totalFunded > 0, "Blockefy: nothing to release");
        require(project.isDeliverableAccepted || _reviewLapsed(project), "Blockefy: deliverable not approved");

        uint256 escrow = project.totalFunded;
        project.totalFunded = 0;
        totalEscrowed -= escrow;
        project.isSubmitted = false;
        project.isDeliverableAccepted = false;
        project.lastReviewAt = 0;

        _payFreelancer(project, escrow);

        project.status = ProjectStatus.Completed;
    }

    // =========================================================================
    //  REFUND
    // =========================================================================

    /**
     * @notice Client retrieves any escrowed funds that are not under review.
     * @param _projectId The project id.
     * @dev Only allowed once the project deadline has passed AND there is escrow that
     *      is not already approved or submitted. This protects an approved
     *      deliverable from being refunded out from under the freelancer.
     */
    function retrieveFunds(uint256 _projectId)
        external
        nonReentrant
        projectExists(_projectId)
        onlyClient(_projectId)
        notDisputed(_projectId)
    {
        Project storage project = projects[_projectId];
        require(project.status != ProjectStatus.Completed, "Blockefy: project already completed");
        require(project.status != ProjectStatus.Cancelled, "Blockefy: project already cancelled");
        require(project.deadline != 0 && block.timestamp > project.deadline, "Blockefy: deadline not passed");
        require(project.totalFunded > 0, "Blockefy: nothing to refund");

        // Never refund a milestone that is already delivered/approved but unreleased.
        uint256[] memory ids = project.milestoneIds;
        for (uint256 i = 0; i < ids.length; i++) {
            Milestone storage m = milestones[ids[i]];
            require(
                !(m.isFunded && !m.isClaimed && (m.isCompleted || m.isApproved)),
                "Blockefy: submitted milestone is under review"
            );
        }
        require(!project.isSubmitted && !project.isDeliverableAccepted, "Blockefy: deliverable under review");

        uint256 refund = project.totalFunded;
        project.totalFunded = 0;
        totalEscrowed -= refund;
        project.status = ProjectStatus.Cancelled;
        project.isSubmitted = false;
        project.isDeliverableAccepted = false;
        project.lastReviewAt = 0;

        (bool success, ) = payable(msg.sender).call{ value: refund }("");
        require(success, "Blockefy: refund failed");

        emit FundsRefunded(_projectId, msg.sender, refund);
    }

    // =========================================================================
    //  DISPUTES
    // =========================================================================

    /**
     * @notice Opens a dispute on a project (locks all payments until resolved).
     * @param _projectId The id of the disputed project.
     * @dev Callable by the CLIENT, the FREELANCER, or the ADMIN. Anyone may freeze a
     *      project that is mid-review; only the ADMIN can resolve it.
     */
    function openDispute(uint256 _projectId)
        external
        projectExists(_projectId)
        onlyParticipant(_projectId)
    {
        Project storage project = projects[_projectId];
        require(project.status != ProjectStatus.Completed, "Blockefy: project already completed");
        require(project.status != ProjectStatus.Cancelled, "Blockefy: project already cancelled");
        require(project.status != ProjectStatus.Disputed, "Blockefy: project already disputed");

        project.status = ProjectStatus.Disputed;

        uint256[] memory ids = project.milestoneIds;
        for (uint256 i = 0; i < ids.length; i++) {
            milestones[ids[i]].isDisputed = true;
        }

        emit DisputeOpened(_projectId, msg.sender);
    }

    /**
     * @notice Resolves a dispute, releasing the remaining escrow to one party.
     * @param _projectId The id of the disputed project.
     * @param _toFreelancer Whether to release the remaining escrow to the freelancer
     *        (true) or refund it to the client (false).
     * @dev Only callable by the ADMIN. Applies the platform fee on a freelancer payout.
     */
    function resolveDispute(uint256 _projectId, bool _toFreelancer)
        external
        nonReentrant
        onlyOwner
        projectExists(_projectId)
    {
        Project storage project = projects[_projectId];
        require(project.status == ProjectStatus.Disputed, "Blockefy: project is not disputed");

        uint256 escrow = project.totalFunded;
        project.totalFunded = 0;
        if (escrow > 0) {
            totalEscrowed -= escrow;
        }

        uint256[] memory ids = project.milestoneIds;
        for (uint256 i = 0; i < ids.length; i++) {
            milestones[ids[i]].isDisputed = false;
            milestones[ids[i]].isCompleted = false;
            milestones[ids[i]].isApproved = false;
        }
        project.isSubmitted = false;
        project.isDeliverableAccepted = false;
        project.lastReviewAt = 0;

        if (escrow > 0) {
            if (_toFreelancer) {
                _payFreelancer(project, escrow);
            } else {
                (bool ok, ) = payable(project.client).call{ value: escrow }("");
                require(ok, "Blockefy: refund failed");
            }
        }

        project.status = ProjectStatus.Completed;
        emit DisputeResolved(_projectId, _toFreelancer);
    }

    // =========================================================================
    //  VIEW / QUERY FUNCTIONS
    // =========================================================================

    /// @notice Returns all milestone ids belonging to a project.
    function getProjectMilestones(uint256 _projectId) external view projectExists(_projectId) returns (uint256[] memory) {
        return projects[_projectId].milestoneIds;
    }

    /// @notice Returns the full list of milestones (as structs) for a project.
    function getMilestonesDetails(uint256 _projectId)
        external
        view
        projectExists(_projectId)
        returns (Milestone[] memory milestonesOut)
    {
        uint256[] memory ids = projects[_projectId].milestoneIds;
        milestonesOut = new Milestone[](ids.length);
        for (uint256 i = 0; i < ids.length; i++) {
            milestonesOut[i] = milestones[ids[i]];
        }
    }

    /// @notice Returns the escrow balance available in the contract for a project.
    function getProjectEscrow(uint256 _projectId) external view projectExists(_projectId) returns (uint256) {
        return projects[_projectId].totalFunded;
    }

    /**
     * @notice Checks whether the review window for a project has lapsed.
     * @param _projectId The project id.
     * @dev Only meaningful while work is submitted and not yet approved.
     */
    function isReviewLapsed(uint256 _projectId) external view projectExists(_projectId) returns (bool) {
        return _reviewLapsed(projects[_projectId]);
    }

    // =========================================================================
    //  INTERNAL / PRIVATE HELPER FUNCTIONS
    // =========================================================================

    /**
     * @dev Validates that a milestone belongs to the given project and is not disputed.
     */
    function _requireValidMilestone(Project storage _project, uint256 _milestoneId) private view {
        require(projectMilestones[_project.id][_milestoneId], "Blockefy: milestone not in project");
        require(!milestones[_milestoneId].isDisputed, "Blockefy: milestone disputed");
    }

    /**
     * @dev Returns the id of the next milestone that still needs to be funded
     *      (strictly in order). Reverts when every milestone is already funded/claimed.
     */
    function _nextUnfundedMilestoneId(Project storage _project) private view returns (uint256) {
        uint256[] memory ids = _project.milestoneIds;
        for (uint256 i = 0; i < ids.length; i++) {
            Milestone storage m = milestones[ids[i]];
            if (!m.isFunded && !m.isClaimed) {
                return ids[i];
            }
        }
        revert("Blockefy: no milestone awaiting funding");
    }

    /**
     * @dev Enforces sequential milestone claiming: all milestones before this one
     *      must have been claimed already.
     */
    function _requirePreviousClaimed(Project storage _project, uint256 _milestoneId) private view {
        uint256[] memory ids = _project.milestoneIds;
        for (uint256 i = 0; i < ids.length; i++) {
            if (ids[i] == _milestoneId) {
                return;
            }
            require(milestones[ids[i]].isClaimed, "Blockefy: previous milestone not claimed");
        }
        revert("Blockefy: milestone not found");
    }

    /**
     * @dev Checks whether the given milestone is the last one in the project.
     */
    function _isLastMilestone(Project storage _project, uint256 _milestoneId) private view returns (bool) {
        uint256[] memory ids = _project.milestoneIds;
        return ids.length > 0 && ids[ids.length - 1] == _milestoneId;
    }

    /**
     * @dev Extends a project's deadline by `_extraDays`, never shortening it.
     *      The base is the later of the current deadline and now, so an extension
     *      requested after the deadline has already lapsed still yields a usable
     *      future deadline.
     */
    function _extendDeadline(Project storage _project, uint256 _extraDays) private {
        require(_extraDays > 0, "Blockefy: extra days must be > 0");
        require(_extraDays <= MAX_DEADLINE_EXTENSION, "Blockefy: extension too long");
        uint256 base = _project.deadline > block.timestamp ? _project.deadline : block.timestamp;
        _project.deadline = base + (_extraDays * 1 days);
    }

    /**
     * @dev Checks whether the client's review window has lapsed after a submission.
     *      Because milestone claiming is strictly sequential, only one milestone is
     *      ever in review at a time, so the project-level timer is correct.
     */
    function _reviewLapsed(Project storage _project) private view returns (bool) {
        if (!_project.isSubmitted) {
            return false;
        }
        return _project.lastReviewAt != 0 &&
               (block.timestamp > _project.lastReviewAt + _project.reviewWindow);
    }

    /**
     * @dev Pays the freelancer, subtracting the platform fee (currently 0%) if any.
     */
    function _payFreelancer(Project storage _project, uint256 _amount) private {
        uint256 fee = (_amount * platformFeeBps) / 10000;
        uint256 net = _amount - fee;

        (bool success, ) = payable(_project.freelancer).call{ value: net }("");
        require(success, "Blockefy: payout failed");

        if (fee > 0) {
            (bool ok, ) = payable(treasury).call{ value: fee }("");
            require(ok, "Blockefy: treasury transfer failed");
        }
    }

    /**
     * @notice Allows the contract to receive ETH directly (e.g. accidental transfers).
     * @dev Such transfers are untracked surplus and can be recovered by the owner via
     *      `sweepSurplus`; they never become part of any project's escrow.
     */
    receive() external payable {}
}
